/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StandingsImport } from './routes/standings'
import { Route as IndexImport } from './routes/index'
import { Route as TeamsIndexImport } from './routes/teams.index'
import { Route as LeaguesIndexImport } from './routes/leagues.index'
import { Route as TeamsTeamIdImport } from './routes/teams.$teamId'
import { Route as LeaguesLeagueIdImport } from './routes/leagues.$leagueId'

// Create/Update Routes

const StandingsRoute = StandingsImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TeamsIndexRoute = TeamsIndexImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRoute,
} as any)

const LeaguesIndexRoute = LeaguesIndexImport.update({
  id: '/leagues/',
  path: '/leagues/',
  getParentRoute: () => rootRoute,
} as any)

const TeamsTeamIdRoute = TeamsTeamIdImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRoute,
} as any)

const LeaguesLeagueIdRoute = LeaguesLeagueIdImport.update({
  id: '/leagues/$leagueId',
  path: '/leagues/$leagueId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsImport
      parentRoute: typeof rootRoute
    }
    '/leagues/$leagueId': {
      id: '/leagues/$leagueId'
      path: '/leagues/$leagueId'
      fullPath: '/leagues/$leagueId'
      preLoaderRoute: typeof LeaguesLeagueIdImport
      parentRoute: typeof rootRoute
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdImport
      parentRoute: typeof rootRoute
    }
    '/leagues/': {
      id: '/leagues/'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LeaguesIndexImport
      parentRoute: typeof rootRoute
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/standings': typeof StandingsRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/leagues': typeof LeaguesIndexRoute
  '/teams': typeof TeamsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/standings': typeof StandingsRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/leagues': typeof LeaguesIndexRoute
  '/teams': typeof TeamsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/standings': typeof StandingsRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/leagues/': typeof LeaguesIndexRoute
  '/teams/': typeof TeamsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/standings'
    | '/leagues/$leagueId'
    | '/teams/$teamId'
    | '/leagues'
    | '/teams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/standings'
    | '/leagues/$leagueId'
    | '/teams/$teamId'
    | '/leagues'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/standings'
    | '/leagues/$leagueId'
    | '/teams/$teamId'
    | '/leagues/'
    | '/teams/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StandingsRoute: typeof StandingsRoute
  LeaguesLeagueIdRoute: typeof LeaguesLeagueIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  LeaguesIndexRoute: typeof LeaguesIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StandingsRoute: StandingsRoute,
  LeaguesLeagueIdRoute: LeaguesLeagueIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  LeaguesIndexRoute: LeaguesIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/standings",
        "/leagues/$leagueId",
        "/teams/$teamId",
        "/leagues/",
        "/teams/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/standings": {
      "filePath": "standings.tsx"
    },
    "/leagues/$leagueId": {
      "filePath": "leagues.$leagueId.tsx"
    },
    "/teams/$teamId": {
      "filePath": "teams.$teamId.tsx"
    },
    "/leagues/": {
      "filePath": "leagues.index.tsx"
    },
    "/teams/": {
      "filePath": "teams.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
